export {
  CaArrowDown,
  CaArrowRight,
  CaArrowUpRight,
  CaBlockStorage,
  CaCheckmarkOutline,
  CaDocument,
  CaDotMark,
  CaEdgeCluster,
  CaExplore,
  CaIntentRequestScaleOut,
  CaGroup,
  CaLogoTwitter,
  CaLogoLinkedin,
  CaLogoGithub,
  CaMoney,
  CaPlayOutline,
  CaRocket,
  CaTask,
  // @ts-ignore
} from '@kalimahapps/vue-icons/ca'
